DIR_SOURCES_SOCA = -Isrc `xml2-config --cflags` -I../../../Soca/src -ILMT/include -Idic

all:
	make -C ../../../Soca
	metil_comp -ne -j1 -O3  $(DIR_SOURCES_SOCA) src/main.cpp

mesher:
	make -C ../../../Soca
	metil_comp -ne -j1 -O3 -g3 $(DIR_SOURCES_SOCA) src/main_gmsh.cpp

gdb:
	metil_comp -ne --gdb -O3 -g3 $(DIR_SOURCES_SOCA) src/main.cpp

val:
	metil_comp -ne --valgrind -O3 -g3 $(DIR_SOURCES_SOCA) src/main.cpp

